// libs/sistema/src/lib/progress/spinner/spinner.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { Size } from '@guillotinaweb/pastanaga-angular';

@Component({
    selector: 'nsi-spinner',
    templateUrl: './spinner.component.html',
    styleUrls: ['./spinner.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SpinnerComponent {
  @Input()
  set size(value: Size | undefined) {
    if (value) {
      this._size = value;
    }
  }
  get size() {
    return this._size;
  }

  private _size: Size = 'medium';
}

<div
  class="spinner-wrapper"
  [class]="size">
  <div class="spinner">
    <div class="inner">
      <div class="gap"></div>
      <div class="left">
        <div class="half-circle"></div>
      </div>
      <div class="right">
        <div class="half-circle"></div>
      </div>
    </div>
  </div>
</div>

// libs/search-widget/src/common/spinner/Spinner.svelte
<script>
  export let size = 'medium';

  let sizeVar;
  $: {
    switch (size) {
      case 'small':
        sizeVar = `var(--rhythm-4)`;
        break;
      case 'large':
        sizeVar = `var(--rhythm-12)`;
        break;
      default:
        sizeVar = '';
    }
  }
</script>

<div
  class="sw-spinner-wrapper"
  style:--inner-size={sizeVar}>
  <div class="spinner">
    <div class="inner">
      <div class="gap" />
      <div class="left">
        <div class="half-circle" />
      </div>
      <div class="right">
        <div class="half-circle" />
      </div>
    </div>
  </div>
</div>

<style
  lang="scss"
  src="./Spinner.scss"></style>
